require: rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**
  NewCops: enable
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
